# Generated by Django 4.2.10 on 2026-02-07 09:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('clinics', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Erkak'), ('female', 'Ayol'), ('other', 'Boshqa')], max_length=20, verbose_name='gender')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('blood_type', models.CharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=10, verbose_name='blood type')),
                ('national_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='national ID')),
                ('insurance_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='insurance ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='phone number')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('country', models.CharField(default='Uzbekistan', max_length=100, verbose_name='country')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255, verbose_name='emergency contact name')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, verbose_name='emergency contact phone')),
                ('allergies', models.TextField(blank=True, help_text="Bemor allergialariga haqida ma'lumot", verbose_name='allergies')),
                ('chronic_diseases', models.TextField(blank=True, help_text='Surunkali kasalliklari', verbose_name='chronic diseases')),
                ('medications', models.TextField(blank=True, help_text='Hozirda qabul qilyotgan dorilar', verbose_name='medications')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('clinics', models.ManyToManyField(blank=True, help_text="Bemor bog'langan klinikalar", related_name='patients', to='clinics.clinic')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientMedicalHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('condition', models.CharField(max_length=255, verbose_name='condition')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('diagnosed_date', models.DateField(blank=True, null=True, verbose_name='diagnosed date')),
                ('status', models.CharField(choices=[('ongoing', 'Davom etayotgan'), ('recovered', 'Tiklab olingan'), ('chronic', 'Surunkali')], default='ongoing', max_length=50, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Medical History',
                'verbose_name_plural': 'Medical Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientDoctorRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
                ('comment', models.TextField(blank=True, help_text='Reytingi ishiga doir izoh', verbose_name='comment')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='anonymous')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_ratings', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Doctor Rating',
                'verbose_name_plural': 'Doctor Ratings',
            },
        ),
    ]
