# Generated by Django 4.2.10 on 2026-02-07 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='patientdoctorrating',
            unique_together={('patient', 'doctor')},
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['user'], name='patients_pa_user_id_b78fa3_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['-created_at'], name='patients_pa_created_15d2a5_idx'),
        ),
    ]
