# Generated by GitHub Copilot on 2026-02-21

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                help_text="Bemor yoshi (ixtiyoriy). Agar date_of_birth bo'lsa, yosh avtomatik hisoblanadi.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(130),
                ],
                verbose_name='age',
            ),
        ),
    ]
