# Generated by Django 4.2.10 on 2026-02-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='no_show_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='How many times the patient was marked as NO_SHOW', verbose_name='no show count'),
        ),
        migrations.AddField(
            model_name='patient',
            name='requires_deposit',
            field=models.BooleanField(default=False, help_text='If true, patient must pay deposit before booking next appointment', verbose_name='requires deposit'),
        ),
    ]
