# Generated by Django 4.2.10 on 2026-07-24 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patient_profile_health_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='national_id',
        ),
    ]
