# Generated by Django 4.2.10 on 2026-10-06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_patient_telegram_chat_id_patient_telegram_linked_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMedicationReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=255, verbose_name='medication name')),
                ('interval_hours', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)], verbose_name='interval hours')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('next_reminder_at', models.DateTimeField(verbose_name='next reminder at')),
                ('last_message_key', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_reminders', to='patients.patient')),
            ],
            options={
                'ordering': ['next_reminder_at', 'created_at'],
                'indexes': [
                    models.Index(fields=['is_active', 'next_reminder_at'], name='patients_reminder_due_idx'),
                ],
            },
        ),
    ]
