# Generated by Django 4.2.10 on 2026-10-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_medication_reminder_acknowledgement'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmedicationreminder',
            name='daily_times',
            field=models.JSONField(blank=True, default=list, verbose_name='daily reminder times'),
        ),
        migrations.AddField(
            model_name='patientmedicationreminder',
            name='next_scheduled_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
