# Generated by Django 4.2.10 on 2026-10-06 18:29

import django.core.validators
from django.db import migrations, models


def keep_fixed_times_for_existing_reminders(apps, schema_editor):
    Reminder = apps.get_model('patients', 'PatientMedicationReminder')
    Reminder.objects.filter(interval_hours__isnull=False).exclude(daily_times=[]).update(
        interval_hours=None,
        next_reminder_at=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_patientmedicationreminder_daily_times_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmedicationreminder',
            name='interval_hours',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)], verbose_name='interval hours'),
        ),
        migrations.AlterField(
            model_name='patientmedicationreminder',
            name='next_reminder_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='next reminder at'),
        ),
        migrations.RunPython(
            keep_fixed_times_for_existing_reminders,
            migrations.RunPython.noop,
        ),
    ]
