# Generated by Django 4.2.10 on 2026-02-22 07:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContactSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, default='', verbose_name='text')),
                ('telegram_link', models.URLField(blank=True, default='', verbose_name='telegram link')),
                ('phone_number', models.CharField(blank=True, default='', max_length=50, verbose_name='phone number')),
                ('instagram_link', models.URLField(blank=True, default='', verbose_name='instagram link')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='email')),
                ('image', models.ImageField(blank=True, null=True, upload_to='home_contact/%Y/%m/%d/', verbose_name='contact image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Home Contact Settings',
                'verbose_name_plural': 'Home Contact Settings',
                'ordering': ['-updated_at'],
            },
        ),
    ]
