# Generated by Django 4.2.10 on 2026-02-22 08:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontactsettings',
            name='email_display',
            field=models.CharField(blank=True, default='', help_text='Frontendda ko‘rinadigan email. Ixtiyoriy (masalan: support@yourdomain.uz).', max_length=255, verbose_name='email display'),
        ),
        migrations.CreateModel(
            name='ContactLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='name')),
                ('phone_number', models.CharField(blank=True, default='', max_length=50, verbose_name='phone number')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='email')),
                ('message', models.TextField(blank=True, default='', verbose_name='message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Contact Lead',
                'verbose_name_plural': 'Contact Leads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='site_settin_created_10b83f_idx')],
            },
        ),
    ]
