# Generated by Django 4.2.10 on 2026-02-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_homecontactsettings_email_display_contactlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlead',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='is read'),
        ),
        migrations.AddField(
            model_name='contactlead',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='read at'),
        ),
    ]
