# Generated by Django 4.2.10 on 2026-03-02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_contactlead_is_read_contactlead_read_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(db_index=True, max_length=120, verbose_name='alert type')),
                ('message', models.TextField(verbose_name='message')),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='error', max_length=20, verbose_name='severity')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='context')),
                ('traceback', models.TextField(blank=True, default='', verbose_name='traceback')),
                ('is_resolved', models.BooleanField(db_index=True, default=False, verbose_name='is resolved')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_system_alerts', to=settings.AUTH_USER_MODEL, verbose_name='resolved by')),
            ],
            options={
                'verbose_name': 'System Alert',
                'verbose_name_plural': 'System Alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_resolved', '-created_at'], name='site_settin_is_resol_8592fb_idx'), models.Index(fields=['severity', '-created_at'], name='site_settin_severit_be6d7b_idx'), models.Index(fields=['alert_type', '-created_at'], name='site_settin_alert_t_ff87d9_idx')],
            },
        ),
    ]
