# Generated by Django 4.2.10 on 2026-03-12 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_systemalert'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='systemalert',
            new_name='site_settin_is_reso_2c3d42_idx',
            old_name='site_settin_is_resol_8592fb_idx',
        ),
        migrations.RenameIndex(
            model_name='systemalert',
            new_name='site_settin_severit_2e78fa_idx',
            old_name='site_settin_severit_be6d7b_idx',
        ),
        migrations.RenameIndex(
            model_name='systemalert',
            new_name='site_settin_alert_t_b6cecc_idx',
            old_name='site_settin_alert_t_ff87d9_idx',
        ),
    ]
