# Generated by Django 4.2.10 on 2026-02-07 09:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='medicine name')),
                ('generic_name', models.CharField(blank=True, max_length=255, verbose_name='generic name')),
                ('atc_code', models.CharField(blank=True, help_text='Anatomical Therapeutic Chemical kod', max_length=100, verbose_name='ATC code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('dosage_form', models.CharField(blank=True, help_text='masalan, tabletka, suyuqlik, injeksiya', max_length=100, verbose_name='dosage form')),
                ('strength', models.CharField(blank=True, help_text='masalan, 500mg, 2%', max_length=100, verbose_name='strength')),
                ('manufacturer', models.CharField(blank=True, max_length=255, verbose_name='manufacturer')),
                ('is_prescription_required', models.BooleanField(default=False, help_text="Retseptli dori shahar qo'yilsa belgi qo'ying", verbose_name='prescription required')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='pharmacy name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('registration_number', models.CharField(help_text="Noyob ro'yxatdan o'tish raqami", max_length=100, unique=True, verbose_name='registration number')),
                ('license_document', models.FileField(blank=True, null=True, upload_to='pharmacy_licenses/%Y/%m/%d/', verbose_name='license document')),
                ('address', models.CharField(max_length=500, verbose_name='address')),
                ('phone_number', models.CharField(max_length=20, verbose_name='phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('website', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='website')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='pharmacy_logos/%Y/%m/%d/', verbose_name='logo')),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('inactive', 'Faolsiz'), ('suspended', "To'xtatilgan"), ('trial', 'Sinov davri')], default='trial', max_length=20, verbose_name='status')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='blocked')),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='rating')),
                ('total_ratings', models.PositiveIntegerField(default=0, verbose_name='total ratings')),
                ('established_date', models.DateField(blank=True, null=True, verbose_name='established date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Pharmacy',
                'verbose_name_plural': 'Pharmacies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyMarchandise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='batch number')),
                ('expiry_date', models.DateField(verbose_name='expiry date')),
                ('quantity_in_stock', models.PositiveIntegerField(default=0, verbose_name='quantity in stock')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text="So'm da hisob qilinadi", max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='unit price')),
                ('is_available', models.BooleanField(default=True, verbose_name='available')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_stocks', to='pharmacies.medicine')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='pharmacies.pharmacy')),
            ],
            options={
                'verbose_name': 'Pharmacy Merchandise',
                'verbose_name_plural': 'Pharmacy Merchandise',
            },
        ),
    ]
