# Generated by Django 4.2.10 on 2026-02-07 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='owner',
            field=models.OneToOneField(help_text='Dorixona egasi', limit_choices_to={'role': 'pharmacy'}, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['name'], name='pharmacies__name_53be43_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['atc_code'], name='pharmacies__atc_cod_e1eea8_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacymarchandise',
            index=models.Index(fields=['pharmacy', 'is_available'], name='pharmacies__pharmac_eb8b5c_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacymarchandise',
            index=models.Index(fields=['expiry_date'], name='pharmacies__expiry__57d0f1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pharmacymarchandise',
            unique_together={('pharmacy', 'medicine', 'batch_number')},
        ),
        migrations.AddIndex(
            model_name='pharmacy',
            index=models.Index(fields=['slug'], name='pharmacies__slug_ace06e_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacy',
            index=models.Index(fields=['status'], name='pharmacies__status_1e74f8_idx'),
        ),
    ]
