# Generated by Django 4.2.10 on 2026-02-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='working_hours',
            field=models.CharField(default='09:00 - 20:00', help_text='Masalan: 09:00 - 20:00', max_length=100, verbose_name='working hours'),
        ),
    ]
