# Generated by Django 4.2.10 on 2026-03-16 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0007_medicine_category_and_origin'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='medicine',
            new_name='pharmacies__categor_0908e3_idx',
            old_name='pharmacies__catego_9c59ef_idx',
        ),
    ]
