# Generated by Django 4.2.10 on 2026-07-24 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0009_medicine_prefix_search_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='medicine',
            name='pharm_medic_act_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='medicine',
            name='pharm_medic_act_gname_idx',
        ),
    ]
