# Generated by Django 4.2.10 on 2026-02-07 09:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacies', '0001_initial'),
        ('clinics', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='plan name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, help_text="So'm da hisob qilinadi", max_digits=10, verbose_name='monthly price')),
                ('duration_days', models.PositiveIntegerField(default=30, help_text='Obuna muddat kunlarda', verbose_name='duration in days')),
                ('max_doctors', models.PositiveIntegerField(blank=True, help_text="Ortiqcha doktorlar soni (bo'sh = cheksiz)", null=True, verbose_name='max doctors')),
                ('max_patients', models.PositiveIntegerField(blank=True, help_text="Ortiqcha bemorlar soni (bo'sh = cheksiz)", null=True, verbose_name='max patients')),
                ('features', models.JSONField(blank=True, help_text='Rejaning xususiyatlari', null=True, verbose_name='features')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subscriber_type', models.CharField(choices=[('clinic', 'Klinika'), ('pharmacy', 'Dorixona')], max_length=20, verbose_name='subscriber type')),
                ('status', models.CharField(choices=[('trial', 'Sinov davri'), ('pending_payment', "To'lov kutilmoqda"), ('active', 'Aktiv'), ('expired', 'Muddati tugagan'), ('cancelled', 'Bekor qilingan'), ('suspended', "To'xtatilgan")], default='trial', max_length=20, verbose_name='status')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='start date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='end date')),
                ('trial_period_days', models.PositiveIntegerField(default=7, help_text='Sinov davri kunlarda', verbose_name='trial period days')),
                ('trial_end_date', models.DateTimeField(blank=True, null=True, verbose_name='trial end date')),
                ('payment_confirmation_date', models.DateTimeField(blank=True, help_text="To'lov tasdiqlangan sana", null=True, verbose_name='payment confirmation date')),
                ('auto_renewal', models.BooleanField(default=True, help_text='Obuna avtomatik yangilansin mi', verbose_name='auto renewal')),
                ('days_until_expiry', models.IntegerField(default=30, help_text='Qancha kundan keyin obuna tugaydi', verbose_name='days until expiry')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('clinic', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='clinics.clinic')),
                ('pharmacy', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='pharmacies.pharmacy')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text="So'm da hisob qilinadi", max_digits=15, verbose_name='amount')),
                ('payment_method', models.CharField(choices=[('card', 'Bank kartalipsi'), ('bank_transfer', "Bank o'tkazmasi"), ('cash', 'Naqd pul'), ('check', 'Chek')], max_length=50, verbose_name='payment method')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlangan'), ('failed', 'Muvaffaqiyatsiz'), ('cancelled', 'Bekor qilingan'), ('refunded', 'Qaytarilgan')], default='pending', max_length=20, verbose_name='status')),
                ('transaction_id', models.CharField(blank=True, help_text="Xarij to'lovni ID", max_length=255, verbose_name='transaction ID')),
                ('reference_number', models.CharField(blank=True, help_text='Bank referenciya raqami', max_length=255, verbose_name='reference number')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('paid_date', models.DateTimeField(blank=True, null=True, verbose_name='paid date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.subscription')),
            ],
            options={
                'verbose_name': 'Subscription Payment',
                'verbose_name_plural': 'Subscription Payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subscription', 'status'], name='subscriptio_subscri_9ecac2_idx'), models.Index(fields=['status'], name='subscriptio_status_e50501_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status'], name='subscriptio_status_5e8870_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['end_date'], name='subscriptio_end_dat_60694b_idx'),
        ),
    ]
