# Generated by Django 4.2.10 on 2026-03-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_pharmacyresettelegramsession'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clinicresettelegramsession',
            new_name='users_clini_user_id_a7ad85_idx',
            old_name='users_clini_user_id_1d2a89_idx',
        ),
        migrations.RenameIndex(
            model_name='clinicresettelegramsession',
            new_name='users_clini_clinic__7056c7_idx',
            old_name='users_clini_clinic__d7fa72_idx',
        ),
        migrations.RenameIndex(
            model_name='codeverificationlockstate',
            new_name='users_codev_channel_aa8cc9_idx',
            old_name='users_codev_channel_8c9952_idx',
        ),
        migrations.RenameIndex(
            model_name='codeverificationlockstate',
            new_name='users_codev_user_id_743acc_idx',
            old_name='users_codev_user_id_6c0e19_idx',
        ),
        migrations.RenameIndex(
            model_name='patientresettelegramsession',
            new_name='users_patie_user_id_475739_idx',
            old_name='users_patie_user_id_31fb8a_idx',
        ),
        migrations.RenameIndex(
            model_name='patientresettelegramsession',
            new_name='users_patie_patient_68db20_idx',
            old_name='users_patie_patient_5bd4fe_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacyresettelegramsession',
            new_name='users_pharm_user_id_6cee7a_idx',
            old_name='users_pharm_user_id_2a87d8_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacyresettelegramsession',
            new_name='users_pharm_pharmac_d38a39_idx',
            old_name='users_pharm_pharmac_fa65af_idx',
        ),
        migrations.AlterField(
            model_name='codeverificationlockstate',
            name='channel',
            field=models.CharField(choices=[('patient_password_reset', 'Patient password reset'), ('doctor_password_reset', 'Doctor password reset'), ('clinic_password_reset', 'Clinic password reset')], max_length=64),
        ),
    ]
