# Generated by Django 4.2.10 on 2026-02-07 09:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='clinic name')),
                ('slug', models.SlugField(help_text='URL uchun noyob identifikator', unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, help_text="Klinika haqida qisqacha ma'lumot", verbose_name='description')),
                ('address', models.CharField(help_text='Klinikaning manzili', max_length=500, verbose_name='address')),
                ('phone_number', models.CharField(help_text='Klinikaning telefon raqami', max_length=20, verbose_name='phone number')),
                ('email', models.EmailField(help_text='Klinikaning email manzili', max_length=254, verbose_name='email')),
                ('website', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='website')),
                ('registration_number', models.CharField(help_text="Noyob ro'yxatdan o'tish raqami", max_length=100, unique=True, verbose_name='registration number')),
                ('license_document', models.FileField(blank=True, null=True, upload_to='clinic_licenses/%Y/%m/%d/', verbose_name='license document')),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('inactive', 'Faolsiz'), ('suspended', "To'xtatilgan"), ('trial', 'Sinov davri')], default='trial', max_length=20, verbose_name='status')),
                ('is_verified', models.BooleanField(default=False, help_text='Administrator tomonidan tasdiqlangan', verbose_name='verified')),
                ('is_blocked', models.BooleanField(default=False, help_text="Administratorning to'saxalini", verbose_name='blocked')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinic_logos/%Y/%m/%d/', verbose_name='logo')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='clinic_banners/%Y/%m/%d/', verbose_name='banner image')),
                ('established_date', models.DateField(blank=True, null=True, verbose_name='established date')),
                ('rating', models.FloatField(default=0.0, help_text="Foydalanuvchilar bergan o'rtacha reytingi (0-5)", validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='rating')),
                ('total_ratings', models.PositiveIntegerField(default=0, help_text='Jami reytingi bergan foydalanuvchilar soni', verbose_name='total ratings')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Clinic',
                'verbose_name_plural': 'Clinics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicDepartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='department name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='clinics.clinic')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='ClinicService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='service name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, help_text="So'm da hisob qilinadi", max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='clinics.clinic')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='clinics.clinicdepartment')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
