# Generated by Django 4.2.10 on 2026-02-07 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicdepartment',
            name='head_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='doctors.doctor'),
        ),
    ]
