# Generated by Django 4.2.10 on 2026-02-07 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='owner',
            field=models.OneToOneField(help_text='Klinika egasi', limit_choices_to={'role': 'clinic'}, on_delete=django.db.models.deletion.CASCADE, related_name='clinic', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='clinicservice',
            index=models.Index(fields=['clinic', 'is_active'], name='clinics_cli_clinic__f432a6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clinicdepartment',
            unique_together={('clinic', 'name')},
        ),
        migrations.AddIndex(
            model_name='clinic',
            index=models.Index(fields=['slug'], name='clinics_cli_slug_c0ea0f_idx'),
        ),
        migrations.AddIndex(
            model_name='clinic',
            index=models.Index(fields=['status'], name='clinics_cli_status_735de3_idx'),
        ),
        migrations.AddIndex(
            model_name='clinic',
            index=models.Index(fields=['-created_at'], name='clinics_cli_created_d351bb_idx'),
        ),
        migrations.AddIndex(
            model_name='clinic',
            index=models.Index(fields=['registration_number'], name='clinics_cli_registr_fae5cc_idx'),
        ),
    ]
