# Generated by Django 4.2.10 on 2026-02-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text="To'lov miqdori", max_digits=12, verbose_name='payment amount'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='payment_description',
            field=models.TextField(blank=True, help_text="To'lov haqida ta'rif", verbose_name='payment description'),
        ),
    ]
