# Generated by Django 4.2.10 on 2026-02-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_clinic_amount_clinic_payment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='payment_date',
            field=models.DateTimeField(blank=True, help_text="To'lov miqdori o'rnatilgan sana", null=True, verbose_name='payment date'),
        ),
    ]
