# Generated by Django 4.2.10 on 2026-08-19 04:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0010_clinic_reception_room_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceptionStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pinfl', models.CharField(max_length=14)),
                ('passport_id', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('password_hash', models.CharField(blank=True, max_length=128)),
                ('available_from', models.TimeField(default='09:00')),
                ('available_until', models.TimeField(default='18:00')),
                ('working_days', models.CharField(default='Mon,Tue,Wed,Thu,Fri', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reception_staff', to='clinics.clinic')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
                'indexes': [models.Index(fields=['clinic', 'is_active'], name='clinics_rec_clinic__a3b780_idx')],
            },
        ),
    ]
