# Generated by Django 4.2.10 on 2026-08-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0014_receptionstaff_work_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='queue_ticket_clinic_address',
            field=models.CharField(blank=True, default='', help_text="Navbat qog'ozida ko'rsatiladigan klinika manzili", max_length=500, verbose_name='queue ticket clinic address'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='queue_ticket_clinic_name',
            field=models.CharField(blank=True, default='', help_text="Navbat qog'ozida ko'rsatiladigan klinika nomi", max_length=255, verbose_name='queue ticket clinic name'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='queue_ticket_contact_url',
            field=models.CharField(blank=True, default='', help_text="Navbat qog'ozida ko'rsatiladigan Telegram/Instagram/yoki URL", max_length=255, verbose_name='queue ticket contact url'),
        ),
    ]
