# Generated by Django 4.2.10 on 2026-08-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0015_clinic_queue_ticket_clinic_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='queue_ticket_number_size',
            field=models.CharField(choices=[('small', 'Kichik'), ('medium', 'O‘rta'), ('large', 'Katta')], default='large', help_text='Navbat raqamining qog‘ozdagi shrift o‘lchami', max_length=10, verbose_name='queue ticket number size'),
        ),
    ]
