# Generated by Django 4.2.10 on 2026-09-28 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('level', models.CharField(choices=[('region', 'Viloyat / shahar'), ('district', 'Tuman / shahar'), ('mahalla', 'Mahalla')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='child_safety.safetyregion')),
            ],
            options={
                'db_table': 'child_safety_regions',
                'ordering': ('level', 'name'),
            },
        ),
        migrations.CreateModel(
            name='SafetyVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('safe', 'Xavfsiz'), ('caution', 'Ehtiyot bo‘lish kerak'), ('danger', 'Xavfsizlik muammolari bor')], max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.TextField(blank=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='child_safety.safetyregion')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_child_safety_votes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='child_safety_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'child_safety_votes',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SafetyVoteAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('cast', 'Ovoz berildi'), ('revoke', 'Ovoz moderator tomonidan bekor qilindi')], max_length=12)),
                ('choice', models.CharField(blank=True, choices=[('safe', 'Xavfsiz'), ('caution', 'Ehtiyot bo‘lish kerak'), ('danger', 'Xavfsizlik muammolari bor')], max_length=12)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_safety_audit_events', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vote_audit', to='child_safety.safetyregion')),
                ('vote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='child_safety.safetyvote')),
            ],
            options={
                'db_table': 'child_safety_vote_audit',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['region', '-created_at'], name='child_safet_region__983029_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='safetyvote',
            index=models.Index(fields=['region', 'is_active', 'choice'], name='child_safet_region__e3431c_idx'),
        ),
        migrations.AddConstraint(
            model_name='safetyvote',
            constraint=models.UniqueConstraint(fields=('user', 'region'), name='child_safety_one_vote_per_user_region'),
        ),
        migrations.AddConstraint(
            model_name='safetyvote',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('is_active', True), ('revoked_at__isnull', True), ('revoked_by__isnull', True)), models.Q(('is_active', False), ('revoked_at__isnull', False), ('revoked_by__isnull', False)), _connector='OR'), name='child_safety_vote_revocation_consistent'),
        ),
        migrations.AddIndex(
            model_name='safetyregion',
            index=models.Index(fields=['parent', 'is_active'], name='child_safet_parent__c07f33_idx'),
        ),
        migrations.AddConstraint(
            model_name='safetyregion',
            constraint=models.UniqueConstraint(fields=('parent', 'level', 'name'), name='child_safety_unique_sibling_region'),
        ),
        migrations.AddConstraint(
            model_name='safetyregion',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('level', 'region'), ('parent__isnull', True)), models.Q(('level__in', ('district', 'mahalla')), ('parent__isnull', False)), _connector='OR'), name='child_safety_region_parent_required'),
        ),
    ]
