# Generated by Django 4.2.10 on 2026-09-28 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('child_safety', '0001_initial'),
    ]

    operations = []
