# Generated by Django 4.2.10 on 2026-09-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child_safety', '0002_alter_safetyregion_id_alter_safetyvote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyvoteaudit',
            name='reason_category',
            field=models.CharField(blank=True, choices=[('abuse', 'Abuse'), ('fraud', 'Fraud')], max_length=12),
        ),
    ]
