# Generated by Django 4.2.10 on 2026-02-07 09:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_number', models.CharField(help_text='Tibbiy litsenziya raqami', max_length=100, unique=True, verbose_name='license number')),
                ('license_document', models.FileField(blank=True, null=True, upload_to='doctor_licenses/%Y/%m/%d/', verbose_name='license document')),
                ('bio', models.TextField(blank=True, help_text="Doktor haqida qisqacha ma'lumot", verbose_name='biography')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='doctor_profiles/%Y/%m/%d/', verbose_name='profile image')),
                ('years_of_experience', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='years of experience')),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, help_text="So'm da hisob qilinadi", max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='consultation fee')),
                ('available_from', models.TimeField(default='09:00', verbose_name='available from')),
                ('available_until', models.TimeField(default='17:00', verbose_name='available until')),
                ('working_days', models.CharField(default='Mon,Tue,Wed,Thu,Fri', help_text='Kun nomlari comma bilan ajratilgan', max_length=100, verbose_name='working days')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_verified', models.BooleanField(default=False, help_text='Administrator tomonidan tasdiqlangan', verbose_name='verified')),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='rating')),
                ('total_ratings', models.PositiveIntegerField(default=0, verbose_name='total ratings')),
                ('total_patients', models.PositiveIntegerField(default=0, verbose_name='total patients')),
                ('consultation_count', models.PositiveIntegerField(default=0, verbose_name='consultation count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('clinic', models.ForeignKey(help_text='Doktor tegishli klinika', on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='clinics.clinic')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='specialization name')),
                ('code', models.CharField(help_text='Noyob kodi (masalan, CARD)', max_length=50, unique=True, verbose_name='code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Specialization',
                'verbose_name_plural': 'Specializations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='date')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('status', models.CharField(choices=[('available', 'Mavjud'), ('booked', 'Band qilingan'), ('unavailable', 'Mavjud emas')], default='available', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'Doctor Availability',
                'verbose_name_plural': 'Doctor Availabilities',
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='specializations',
            field=models.ManyToManyField(blank=True, help_text='Doktor ixtisosliklari', related_name='doctors', to='doctors.specialization'),
        ),
    ]
