# Generated by Django 4.2.10 on 2026-02-07 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='doctoravailability',
            unique_together={('doctor', 'date', 'start_time')},
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['clinic', 'is_active'], name='doctors_doc_clinic__afa889_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['-rating'], name='doctors_doc_rating_042358_idx'),
        ),
    ]
