# Generated by Django 4.2.10 on 2026-02-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, help_text='Doktor ishga kelgan vaqti', null=True, verbose_name='checked in at'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='checked_out_at',
            field=models.DateTimeField(blank=True, help_text='Doktor ishdan chiqgan vaqti', null=True, verbose_name='checked out at'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_checked_in',
            field=models.BooleanField(default=False, help_text="Doktor hozir ishda ekanligini ko'rsatadi", verbose_name='is checked in'),
        ),
    ]
