# Generated by Django 4.2.10 on 2026-02-09 09:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_checked_in_at_doctor_checked_out_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorWorkRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Ish kunining sanasi', verbose_name='date')),
                ('checked_in_at', models.TimeField(blank=True, help_text='Ishga kelgan vaqti', null=True, verbose_name='checked in at')),
                ('checked_out_at', models.TimeField(blank=True, help_text='Ishdan chiqgan vaqti', null=True, verbose_name='checked out at')),
                ('work_duration', models.DecimalField(decimal_places=2, default=0, help_text='Ish vaqti (soat)', max_digits=5, verbose_name='work duration')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('doctor', models.ForeignKey(help_text='Doktor', on_delete=django.db.models.deletion.CASCADE, related_name='work_records', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'Doctor Work Record',
                'verbose_name_plural': 'Doctor Work Records',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['doctor', 'date'], name='doctors_doc_doctor__d0b4b4_idx'), models.Index(fields=['doctor', '-date'], name='doctors_doc_doctor__158555_idx')],
                'unique_together': {('doctor', 'date')},
            },
        ),
    ]
