# Generated by Django 4.2.10 on 2026-02-12 11:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctorworkrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSpecialization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, help_text="Ushbu ixtisoslik uchun konsultatsiya narxi (So'm)", max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='consultation fee')),
                ('is_active', models.BooleanField(default=True, help_text='Bu ixtisoslik faol yoki faol emas', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialty_prices', to='doctors.doctor')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_prices', to='doctors.specialization')),
            ],
            options={
                'verbose_name': 'Doctor Specialization',
                'verbose_name_plural': 'Doctor Specializations',
                'ordering': ['specialization__name'],
                'indexes': [models.Index(fields=['doctor', 'is_active'], name='doctors_doc_doctor__59a4ca_idx')],
                'unique_together': {('doctor', 'specialization')},
            },
        ),
    ]
