# Generated by Django 4.2.10 on 2026-02-23 05:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_doctorspecialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='slot_minutes',
            field=models.PositiveSmallIntegerField(choices=[(15, '15'), (20, '20'), (30, '30')], default=30, help_text='Appointment slot duration in minutes (15/20/30)', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(30)], verbose_name='slot minutes'),
        ),
    ]
