# Generated by Django 4.2.10 on 2026-03-12 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0008_clinic_owner_passport_id'),
        ('doctors', '0015_doctoremployment_compensation_snapshot'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='doctoremployment',
            new_name='doctors_doc_doctor__b70c1a_idx',
            old_name='doctors_doc_doctor__4c2317_idx',
        ),
        migrations.RenameIndex(
            model_name='doctoremployment',
            new_name='doctors_doc_clinic__dd89a9_idx',
            old_name='doctors_doc_clinic__c69c44_idx',
        ),
        migrations.RenameIndex(
            model_name='doctoremployment',
            new_name='doctors_doc_doctor__3c2b58_idx',
            old_name='doctors_doc_doctor__f2a1bf_idx',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='clinic',
            field=models.ForeignKey(blank=True, help_text='Doktor tegishli klinika', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='clinics.clinic'),
        ),
    ]
