# Generated by Django 4.2.10 on 2026-08-05 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0019_alter_doctor_slot_minutes_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctors'},
        ),
        migrations.RenameIndex(
            model_name='doctor',
            new_name='doctors_doc_clinic__ea9c2f_idx',
            old_name='doc_clinic_disp_ord_idx',
        ),
    ]
