# Generated by Django 4.2.10 on 2026-08-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0023_restore_clinic_specialty_ownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorspecialization',
            name='custom_name',
            field=models.CharField(blank=True, help_text="Doktor o'zi kiritgan yo'nalish nomi (faqat doctor_custom uchun, umumiy ixtisoslik ro'yxatiga ta'sir qilmaydi)", max_length=255, verbose_name='custom name'),
        ),
    ]
