# Generated by Django 4.2.10 on 2026-02-07 09:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_type', models.CharField(choices=[('consultation', 'Maslahat'), ('follow_up', 'Tekshiruv'), ('procedure', 'Operatsiya'), ('test', 'Sinov')], default='consultation', max_length=20, verbose_name='appointment type')),
                ('status', models.CharField(choices=[('scheduled', 'Rejalashtirilgan'), ('completed', 'Bajarilgan'), ('cancelled', 'Bekor qilingan'), ('no_show', 'Kelmagandi')], default='scheduled', max_length=20, verbose_name='status')),
                ('scheduled_date', models.DateTimeField(verbose_name='scheduled date')),
                ('duration_minutes', models.PositiveIntegerField(default=30, verbose_name='duration in minutes')),
                ('reason', models.TextField(blank=True, verbose_name='reason for visit')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='consultation fee')),
                ('is_paid', models.BooleanField(default=False, verbose_name='paid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diagnosis_code', models.CharField(blank=True, help_text='ICD-10 kodi', max_length=100, verbose_name='diagnosis code')),
                ('diagnosis_name', models.CharField(max_length=500, verbose_name='diagnosis name')),
                ('certainty', models.CharField(choices=[('confirmed', 'Tasdiqlangan'), ('probable', 'Ehtimol'), ('provisional', 'Vaqtiy')], default='confirmed', max_length=20, verbose_name='certainty')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('is_primary', models.BooleanField(default=False, help_text="Asosiy tashxis bo'lsa belgi qo'ying", verbose_name='primary diagnosis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Diagnosis',
                'verbose_name_plural': 'Diagnoses',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=255, verbose_name='test name')),
                ('test_code', models.CharField(blank=True, max_length=100, verbose_name='test code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('status', models.CharField(choices=[('ordered', 'Muddaao etilgan'), ('in_progress', 'Davom etayotgan'), ('completed', 'Bajarilgan'), ('cancelled', 'Bekor qilingan')], default='ordered', max_length=20, verbose_name='status')),
                ('ordered_date', models.DateTimeField(auto_now_add=True, verbose_name='ordered date')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='scheduled date')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='completed date')),
                ('results', models.JSONField(blank=True, help_text='Sinov natijalarini JSON formatida', null=True, verbose_name='test results')),
                ('normal_range', models.CharField(blank=True, max_length=255, verbose_name='normal range')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'Lab Test',
                'verbose_name_plural': 'Lab Tests',
                'ordering': ['-ordered_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chief_complaint', models.TextField(blank=True, help_text='Bemorning asosiy shikoyati', verbose_name='chief complaint')),
                ('vital_signs', models.JSONField(blank=True, help_text='Harorat, bosim, duch-dumi va xokazo', null=True, verbose_name='vital signs')),
                ('examination_findings', models.TextField(blank=True, help_text='Jismoniy tekshiruv natijasi', verbose_name='examination findings')),
                ('assessment', models.TextField(blank=True, help_text='Doktorning baholash va tashxisi', verbose_name='assessment')),
                ('plan', models.TextField(blank=True, help_text='Davolash rejasi va tavsiyalar', verbose_name='plan')),
                ('is_locked', models.BooleanField(default=False, help_text="Yozuv yakuniy bo'lsa belgi qo'ying", verbose_name='locked')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Medical Record',
                'verbose_name_plural': 'Medical Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dosage', models.CharField(help_text='masalan, 1 tabletka, kun 3 marta', max_length=200, verbose_name='dosage')),
                ('frequency', models.CharField(help_text='qancha muddat davomida', max_length=200, verbose_name='frequency')),
                ('duration_days', models.PositiveIntegerField(default=7, verbose_name='duration in days')),
                ('instructions', models.TextField(blank=True, help_text="Qo'shimcha ko'rsatmalar", verbose_name='special instructions')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('completed', 'Bajarilgan'), ('expired', 'Muddati tugagan'), ('cancelled', 'Bekor qilingan')], default='active', max_length=20, verbose_name='status')),
                ('issued_date', models.DateTimeField(auto_now_add=True, verbose_name='issued date')),
                ('expiry_date', models.DateField(blank=True, help_text='Retsept qancha vaqtgacha haqiqiy', null=True, verbose_name='expiry date')),
                ('is_filled', models.BooleanField(default=False, verbose_name='filled')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'ordering': ['-issued_date'],
            },
        ),
    ]
