# Generated by Django 4.2.10 on 2026-02-07 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        ('pharmacies', '0001_initial'),
        ('clinics', '0002_initial'),
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='filled_at_pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='pharmacies.pharmacy'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='medical.medicalrecord'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='pharmacies.medicine'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_record', to='medical.appointment'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='clinics.clinic'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='medical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='medical.medicalrecord'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='medical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='medical.medicalrecord'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinics.clinic'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', 'status'], name='medical_pre_patient_fae05f_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['doctor', '-issued_date'], name='medical_pre_doctor__8c1496_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['expiry_date'], name='medical_pre_expiry__dbb7ae_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['patient', '-created_at'], name='medical_med_patient_6b594f_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['doctor', '-created_at'], name='medical_med_doctor__538a87_idx'),
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['patient', 'status'], name='medical_lab_patient_447275_idx'),
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['ordered_date'], name='medical_lab_ordered_9975fb_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'scheduled_date'], name='medical_app_patient_97390a_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'scheduled_date'], name='medical_app_doctor__d9e159_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='medical_app_status_eca649_idx'),
        ),
    ]
