# Generated by Django 4.2.10 on 2026-02-13 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0005_clinic_payment_date'),
        ('doctors', '0005_doctorspecialization'),
        ('medical', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='clinic_name',
            field=models.CharField(blank=True, help_text='Klinika nomi (arxiv uchun)', max_length=255, verbose_name='clinic name'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_name',
            field=models.CharField(blank=True, help_text='Doktor nomi (arxiv uchun)', max_length=255, verbose_name='doctor name'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='clinic_name',
            field=models.CharField(blank=True, help_text='Klinika nomi (arxiv uchun)', max_length=255, verbose_name='clinic name'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='doctor_name',
            field=models.CharField(blank=True, help_text='Doktor nomi (arxiv uchun)', max_length=255, verbose_name='doctor name'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='clinics.clinic'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='clinics.clinic'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='doctors.doctor'),
        ),
    ]
