# Generated by Django 4.2.10 on 2026-02-13 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_doctorspecialization'),
        ('medical', '0003_appointment_clinic_name_appointment_doctor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='doctor_name',
            field=models.CharField(blank=True, help_text='Doktor nomi (arxiv uchun)', max_length=255, verbose_name='doctor name'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor_name',
            field=models.CharField(blank=True, help_text='Doktor nomi (arxiv uchun)', max_length=255, verbose_name='doctor name'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='doctor',
            field=models.ForeignKey(blank=True, help_text="Laboratoriya testini buyurgan doktor (o'chirilgan bo'lsa NULL)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests', to='doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(blank=True, help_text="Retsept bergan doktor (o'chirilgan bo'lsa NULL)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='doctors.doctor'),
        ),
    ]
