# Generated by Django 4.2.10 on 2026-02-23 05:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_doctor_slot_minutes'),
        ('medical', '0004_labtest_doctor_name_prescription_doctor_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramConversationState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_user_id', models.BigIntegerField(db_index=True, verbose_name='telegram user id')),
                ('action', models.CharField(choices=[('reschedule_awaiting_datetime', 'Reschedule awaiting datetime')], max_length=64, verbose_name='action')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='queue_position',
            field=models.PositiveIntegerField(default=0, help_text='Ordering position for doctor queue on the given day', verbose_name='queue position'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='slot',
            field=models.ForeignKey(blank=True, help_text='Booked availability slot (used to free slot on cancellation)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='doctors.doctoravailability'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='telegram chat id'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='telegram_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='telegram confirmed at'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='telegram_token',
            field=models.UUIDField(blank=True, help_text='One-time token used for Telegram /start linking', null=True, unique=True, verbose_name='telegram token'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='telegram_token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='telegram token expires at'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='telegram_user_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='telegram user id'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending_telegram_confirmation', 'Telegram tasdiqi kutilmoqda'), ('confirmed', 'Tasdiqlangan'), ('waiting', 'Kutilmoqda'), ('in_progress', 'Jarayonda'), ('scheduled', 'Rejalashtirilgan'), ('completed', 'Bajarilgan'), ('cancelled', 'Bekor qilingan'), ('no_show', 'Kelmagandi')], default='scheduled', max_length=40, verbose_name='status'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['telegram_user_id', 'scheduled_date'], name='medical_app_telegra_244be4_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['telegram_token'], name='medical_app_telegra_9a2e0e_idx'),
        ),
        migrations.AddField(
            model_name='telegramconversationstate',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_states', to='medical.appointment'),
        ),
        migrations.AddIndex(
            model_name='telegramconversationstate',
            index=models.Index(fields=['telegram_user_id', 'expires_at'], name='medical_tel_telegra_0a72c5_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramconversationstate',
            index=models.Index(fields=['appointment', 'expires_at'], name='medical_tel_appoint_3b9f4f_idx'),
        ),
    ]
