# Generated by Django 4.2.10 on 2026-02-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_telegramconversationstate_appointment_queue_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='telegram_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='telegram reminder sent at'),
        ),
    ]
