# Generated by Django 4.2.10 on 2026-02-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_appointment_telegram_reminder_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_arrival_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='Set when patient taps "Boraman" on the 15-minute Telegram prompt', null=True, verbose_name='patient arrival confirmed at'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='telegram_15min_prompt_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='telegram 15min prompt sent at'),
        ),
    ]
