# Generated by Django 4.2.10 on 2026-07-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0007_appointment_patient_arrival_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='telegram_two_left_notified_at',
            field=models.DateTimeField(blank=True, help_text='Set when patient is notified that only 2 people are ahead in queue', null=True, verbose_name='telegram two left notified at'),
        ),
    ]
