# Generated by Django 4.2.10 on 2026-07-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0008_appointment_telegram_two_left_notified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='telegram_one_left_notified_at',
            field=models.DateTimeField(blank=True, help_text='Set when patient is notified that only 1 person is ahead in queue', null=True, verbose_name='telegram one left notified at'),
        ),
    ]
