# Generated by Django 4.2.10 on 2026-08-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0011_alter_appointment_auto_turn_response_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramconversationstate',
            name='action',
            field=models.CharField(choices=[('reschedule_awaiting_datetime', 'Reschedule awaiting datetime'), ('rating_awaiting_comment', 'Rating awaiting comment')], max_length=64, verbose_name='action'),
        ),
    ]
