# Generated by Django 4.2.10 on 2026-08-19 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinics', '0014_receptionstaff_work_record'),
        ('medical', '0015_appointment_reception_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_name', models.CharField(default='G-MED Printer Device', help_text='Lokal qurilma nomi', max_length=120)),
                ('printer_name', models.CharField(blank=True, default='', help_text='Masalan: Xprinter XP-Q200', max_length=150)),
                ('device_token', models.CharField(help_text='Printer service uchun maxsus token', max_length=200, unique=True)),
                ('status', models.CharField(choices=[('ready', 'Ulangan va tayyor'), ('checking', 'Tekshirilmoqda / band'), ('offline', 'Printer Service offline'), ('disconnected', 'Ulanmagan')], default='offline', max_length=30)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printer_devices', to='clinics.clinic')),
                ('reception_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printer_devices', to='clinics.clinicdepartment')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('printing', 'printing'), ('completed', 'completed'), ('failed', 'failed')], default='pending', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to='medical.appointment')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='clinics.clinic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to=settings.AUTH_USER_MODEL)),
                ('printer_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='printers.printerdevice')),
                ('reception_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to='clinics.clinicdepartment')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['clinic', 'status'], name='printers_pr_clinic__a4b0b7_idx'), models.Index(fields=['printer_device', 'status'], name='printers_pr_printer_ab6643_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='printerdevice',
            index=models.Index(fields=['clinic', 'status'], name='printers_pr_clinic__4d5b83_idx'),
        ),
        migrations.AddIndex(
            model_name='printerdevice',
            index=models.Index(fields=['device_token'], name='printers_pr_device__d3a7c8_idx'),
        ),
    ]
