# Generated by Django 4.2.10 on 2026-02-07 09:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('clinics', '0002_initial'),
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=100, unique=True, verbose_name='invoice number')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('issued', 'Chiqarilgan'), ('paid', "To'landi"), ('overdue', "Muddatidan o'tgan"), ('cancelled', 'Bekor qilingan')], default='draft', max_length=20, verbose_name='status')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total amount')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='tax amount')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='discount amount')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='net amount')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='paid amount')),
                ('payment_terms', models.CharField(blank=True, max_length=255, verbose_name='payment terms')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='due date')),
                ('issued_date', models.DateField(auto_now_add=True, verbose_name='issued date')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='paid date')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('consultation', 'Maslahat'), ('service', 'Xizmat'), ('medicine', 'Dori'), ('test', 'Sinov'), ('subscription', 'Obuna')], max_length=50, verbose_name='payment type')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlangan'), ('failed', 'Muvaffaqiyatsiz'), ('cancelled', 'Bekor qilingan'), ('refunded', 'Qaytarilgan')], default='pending', max_length=20, verbose_name='status')),
                ('description', models.CharField(max_length=500, verbose_name='description')),
                ('amount', models.DecimalField(decimal_places=2, help_text="So'm da hisob qilinadi", max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='amount')),
                ('payment_method', models.CharField(choices=[('card', 'Bank kartalipsi'), ('bank_transfer', "Bank o'tkazmasi"), ('cash', 'Naqd pul'), ('online_wallet', 'Elektron hamyon')], max_length=50, verbose_name='payment method')),
                ('transaction_id', models.CharField(blank=True, help_text="Xarij to'lovni ID", max_length=255, verbose_name='transaction ID')),
                ('reference_number', models.CharField(blank=True, max_length=255, verbose_name='reference number')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('paid_date', models.DateTimeField(blank=True, null=True, verbose_name='paid date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='medical.appointment')),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received', to='clinics.clinic')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
