# Generated by Django 4.2.10 on 2026-02-14 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text="So'm da hisob qilinadi", max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='amount'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.TextField(blank=True, help_text="To'lov tavsifi", verbose_name='description'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_cancelled_at',
            field=models.DateTimeField(blank=True, help_text="To'lov bekor qilingan vaqti", null=True, verbose_name='payment cancelled at'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_confirmed_at',
            field=models.DateTimeField(blank=True, help_text="To'lov tasdiqlangan vaqti", null=True, verbose_name='payment confirmed at'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_initiated_at',
            field=models.DateTimeField(blank=True, help_text="To'lov jarayoni boshlangan vaqti", null=True, verbose_name='payment initiated at'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('click', 'Click'), ('stripe', 'Stripe'), ('cash', 'Naqd pul'), ('transfer', "Bank o'tkazmasi")], help_text="To'lov usuli", max_length=50, verbose_name='payment method'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_order_id',
            field=models.CharField(blank=True, help_text="Click to'lov buyurtmasi ID", max_length=255, verbose_name='payment order ID'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('not_initiated', "Boshlangani yo'q"), ('initiated', 'Boshlangan'), ('pending_payment', "To'lov kutilmoqda"), ('completed', 'Yakunlangan'), ('failed', 'Muvaffaqiyatsiz'), ('cancelled', 'Bekor qilingan'), ('paid', "To'landi")], default='not_initiated', max_length=50, verbose_name='payment status'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_transaction_id',
            field=models.CharField(blank=True, help_text='Click operatsiya ID', max_length=255, verbose_name='payment transaction ID'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='net amount'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text="So'm da hisob qilinadi", max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='amount'),
        ),
    ]
